sylius_support:
    path: /
    defaults:
        _controller: sylius.controller.support_request:createAction
        _sylius:
            template: SyliusWebBundle:Frontend:support.html.twig
            redirect: sylius_support
