# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_support_request_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.support_request:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/SupportRequest:index.html.twig
            sortable: true
            paginate: false

sylius_backend_support_request_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.support_request:createAction
        _sylius:
            template: SyliusWebBundle:Backend/SupportRequest:create.html.twig
            redirect: sylius_backend_support_request_index

sylius_backend_support_request_update:
    path: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.support_request:updateAction
        _sylius:
            template: SyliusWebBundle:Backend/SupportRequest:update.html.twig
            redirect: sylius_backend_support_request_index

sylius_backend_support_request_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.support_request:deleteAction
        _sylius:
            template: SyliusWebBundle:Backend/Misc:delete.html.twig
            redirect: sylius_backend_support_request_index

sylius_backend_support_request_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.support_request:showAction
        _sylius:
            template: SyliusWebBundle:Backend/SupportRequest:show.html.twig
